### ISSUE TITLE
Error reading theme file

### ISSUE THREAD

**Issue by sladiri** [josefaidt/rouge-theme#1]
@The theme does not load correctly. I get this error in the developer tools:
`shell.ts:454 Unable to load C:\Users\bla\.vscode\extensions\josef.rouge-theme-1.1.1\themes\rouge-theme-syntax.json: Problems parsing JSON theme file: Value expected: Error: Unable to load C:\Users\bla\.vscode\extensions\josef.rouge-theme-1.1.1\themes\rouge-theme-syntax.json: Problems parsing JSON theme file: Value expected`

**Comment by josefaidt** [comment]
Looking into this now. What version of VSCode are you using?
EDIT: found the theme is error-ing out on my machine, too. Will push a patch soon.

**Comment by josefaidt** [comment]
Fixed the issue in [v1.1.2](https://github.com/josefaidt/rouge-theme/releases/tag/v1.1.2). I had an extra comma in the syntax file...

Closing issue
