### ISSUE TITLE
Seeing two different background colors in the editor view

### ISSUE THREAD

**Issue by thevarunraja** [josefaidt/rouge-theme#13]
I am seeing different background colors in the editor view(#182131 for the used area, #172030 for the unused area). I have been using this theme for more than two months, never seen this behavior. Maybe latest VSCode update broke something. I tried to debug the issue but couldn't find the root cause. Please see the screenshot below. 

<img width="1009" alt="screen shot 2019-03-01 at 8 08 13 pm" src="https://user-images.githubusercontent.com/17805098/53674816-9f606d80-3c5e-11e9-9eb5-3110c5e2543c.png">

**Comment by josefaidt** [comment]
Hi @thevarunraja I've also noticed this recently as well! I'm working on a few improvements, will get back to you soon

**Comment by josefaidt** [comment]
@thevarunraja what is your operating system? If macOS, do you notice this when the nightlight is turned on?

I've tried turning the background to red just to see if another color was creeping in somehow, but the entire background was actually red; no weird coloring issues like we see on the theme itself.

I'm continuing to poke around, just wanted to touch base

**Comment by thevarunraja** [comment]
Hey thanks for the reply. My personal machine is running on MacOS Mojave. Idk what nightlight is. This issue is not happening on my work Mac. The settings are also same for work and my personal machine. I disabled all the extensions, and still seeing this issue.

**Comment by josefaidt** [comment]
Hi @thevarunraja, I'm not quite sure what is causing the issue. I notice it will generate blocks of the odd color at a time. I disabled all other extensions and color options except for the background to no avail, but if I change the background the issue does not persist. I am investigating further.

**Comment by josefaidt** [comment]
@thevarunraja this one is stumping me. I've dug through the dev tools and the only odd thing I could find was that sometimes my background color is getting changed from hex and trickled into child elements in RGB. I guess maybe the VSCode renderer is doing this. 

I've been looking for any weird CSS filters, a transparent overlay, etc. Just wanted to let you know I'm still looking into this :)

**Comment by josefaidt** [comment]
Ok, I didn't realize there was a digital color utility on macOS, but I found that the areas with text are slightly off from what my value actually is:

|  | Shown in DevTools | Converted color |
|---|---|---|
| Actual | `#172030` | `rgb(25, 32, 47)` |
| The 'off' color |`rgb(25, 33, 47)` | `#19212f` |

**Comment by thevarunraja** [comment]
I think this might be an issue with VSCode. It's awesome you raised a ticket with VSCode. Other themes are also seeing this issue. Please find the links below. 

[https://github.com/ayu-theme/vscode-ayu/issues/77](https://github.com/ayu-theme/vscode-ayu/issues/77)
[https://github.com/Monokai/monokai-pro-vscode/issues/108](https://github.com/Monokai/monokai-pro-vscode/issues/108)

**Comment by thevarunraja** [comment]
this issue got fixed in insiders build.

**Comment by josefaidt** [comment]
Thanks for the heads up @thevarunraja!! I'll be doing some extra testing this evening, but this is good news!

**Comment by josefaidt** [comment]
@thevarunraja this has been fixed, https://github.com/microsoft/vscode/issues/71123#event-2703909635
