### ISSUE TITLE
HTML attributes not in italics like screenshot

### ISSUE THREAD

**Issue by sfrench87** [josefaidt/rouge-theme#16]
It seems the "[HTML] - Entity Other" rule isn't working, don't know if there is a better way but using "entity.other.attribute-name.html" fixes it for me. Love the theme by the way.

**Comment by josefaidt** [comment]
Hi! Thanks for the kind words! Apologies for getting back to you so late, but I will fix this as soon as possible! I think I broke something along the way and adapted to it without realizing.
