### ISSUE TITLE
Tag styling breaks in .js files

### ISSUE THREAD

**Issue by dancherb** [josefaidt/rouge-theme#2]
Love the theme, have gone through hundreds and can't find one I like more... only thing - I use JSX and React to write html within JavaScript files, and the styling is nowhere near as pretty as it is in plain .html files. Mainly, the "name" of a tag (e.g. div) is the same colour and style as its properties (e.g. class="x"). It's also not in italics like in html files. I've seen this fixed in other themes, so if there's a way, I would love that.

![jsx](https://user-images.githubusercontent.com/32280121/34858251-1d988a6a-f747-11e7-8276-9e26d7def925.png)

**Comment by dancherb** [comment]
Fixed by installing Babel ES6 extension!

**Comment by josefaidt** [comment]
Hey man, just wanted to give you an update on this submission. I just published the new version v1.2.1 which styles the elements in your entry above like their HTML counterparts. 

<img width="226" alt="screen shot 2018-02-12 at 5 49 03 pm" src="https://user-images.githubusercontent.com/5033303/36126187-0f676cc4-101d-11e8-8edd-9a4c914a9a40.png">

I tried a few of those babel extensions and found some skewed styling of other characters, and others that didn't, but I felt I could bake this into the theme. Let me know if you run into any additional issues or if you have any requests!

**Comment by dancherb** [comment]
@josefaidt thanks for the heads up! There is _one_ more thing I noticed, if you're looking for suggestions... the contents of a tag are the same colour as the tag itself, and if the "child" red was a different colour it would be great for readability (for catching text to be rendered on screen as opposed to components and properties).

thanks again!

![rouge2](https://user-images.githubusercontent.com/32280121/36130190-4cbfc026-1063-11e8-8336-ffc47d86ee9b.png)

**Comment by josefaidt** [comment]
Just updated the theme with a few more adjustments. First, I think a babel extension may still be active in that screenshot you posted, just from the colored round braces after `this.addNote`. Second, I updated the text to match the default text and also the styling properties, which also affects object literal keys (honestly I like it). Third, I tweaked the property values to match the CSS styling - for example, if we have `display: flex`, 'flex' will be green. 

Finally, I went ahead and gave the bracket color that of its HTML styling, though I'm not sure what else that could effect.

<img width="510" alt="screen shot 2018-02-12 at 9 29 58 pm" src="https://user-images.githubusercontent.com/5033303/36132458-160bd400-103d-11e8-83fc-91c7dffe91c5.png">

If you have anything else just let me know!

**Comment by dancherb** [comment]
Just noticed that my sidebar buttons on the left have gone silver and I miss the pink, not sure when it happened (thanks again!) @josefaidt 

![sidebar](https://user-images.githubusercontent.com/32280121/36940484-78d2979c-1f3b-11e8-8eb4-cfaac50de3d3.png)

**Comment by josefaidt** [comment]
Hey man, I went silver on this last update to have better contrast with the badges. I'll add em back in the next update, thanks for the feedback!

In the mean time consider adding the following to your settings to put it back:
```json
"workbench.colorCustomizations": {
    "activityBar.foreground": "#c6797e",
}
```

**Comment by josefaidt** [comment]
Hey dancherb, just wanted to give you an update regarding this decision. I went ahead and left the silver as I feel it provides a sleeker feel with more contrast in regards to the icon badges. I've updated my readme to include this option as I've done with the sidebar headers back in v1.1.0. 

If you have any additional requests or concerns please don't hesitate to reach out! Thanks for the feedback!
