### ISSUE TITLE
Separate error and warning colours

### ISSUE THREAD

**Issue by alecks** [josefaidt/rouge-theme#24]
There only seems to be a single colour shared by errors and warnings; this is pretty confusing.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/24289784/86270871-dd0f3680-bbc3-11ea-8c65-e8755524b1db.png">

Could a separate, lighter colour for warnings be considered? If it's already implemented, I'm using an insiders build if that's relevant.

**Comment by josefaidt** [comment]
hey @fjah ! sorry for the delay, yes there are quite a few styles I've been meaning to clean up. Will probably tackle that this weekend.

Quick question, are you using the newer syntax highlighting?

**Comment by alecks** [comment]
No worries! If you mean semantic highlighting, I was but it seems to be reproducible regardless. That was a Rust example.

**Comment by josefaidt** [comment]
How does this look? 
![image](https://user-images.githubusercontent.com/5033303/87551989-b72f6a80-c676-11ea-8493-43109dfe00e4.png)

**Comment by alecks** [comment]
Looks great 👍

**Comment by josefaidt** [comment]
This is now live 🙂 thank you for the heads up
